### PR TITLE
fix: use correct repository on arm64 ubuntu image

### PR DESCRIPTION
**Pull request by nerg4l**
I had to make some changes to be able to use the Dev Container on an arm64 device which pulls arm64 Ubuntu image.

- `http://archive.ubuntu.com/ubuntu` contains releases for: amd64, i386
- `http://ports.ubuntu.com/ubuntu-ports` contains releases for: arm64, armhf, ppc64el, s390x

In this PR I only added a condition for arm64 but other architectures can included.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Mind checking if the latest code works for arm64 now?

**Comment by nerg4l** [comment]
From my understanding the problem is http://**archive**.ubuntu.com/**ubuntu**/dists/jammy-backports/main/binary-arm64/, which should be http://**ports**.ubuntu.com/**ubuntu-ports**/dists/jammy-backports/main/binary-arm64/.

I get the following:

```
#0 9.958 Reading package lists...
#0 10.49 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/main/binary-arm64/Packages  404  Not Found [IP: 185.125.190.39 80]
#0 10.49 E: Some index files failed to download. They have been ignored, or old ones used instead.
#0 10.50 make: *** [Makefile:24: shellcheck] Error 100
------
[2023-12-10T09:08:32.670Z] ERROR: failed to solve: executor failed running [/bin/bash -o pipefail -c source /tmp/.env &&   dokku plugin:install file:///tmp --name $PLUGIN_NAME &&   make ci-dependencies]: exit code: 2
[2023-12-10T09:08:32.678Z] Stop (11811 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/6f/vxj52db140g8jb8j8gp4p7sh0000gn/T/devcontainercli/container-features/0.54.1-1702199300866/Dockerfile-with-features -t vsc-dokku-redis-0306dd26c362be39f5387c51162a0481b1f4c1bb436fc668970797b2b7150713 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/lgorog/GolandProjects/nerg4l/dokku-redis
[2023-12-10T09:08:32.679Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/6f/vxj52db140g8jb8j8gp4p7sh0000gn/T/devcontainercli/container-features/0.54.1-1702199300866/Dockerfile-with-features -t vsc-dokku-redis-0306dd26c362be39f5387c51162a0481b1f4c1bb436fc668970797b2b7150713 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/lgorog/GolandProjects/nerg4l/dokku-redis
[2023-12-10T09:08:32.679Z]     at Y$ (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:463:1860)
[2023-12-10T09:08:32.679Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-12-10T09:08:32.679Z]     at async Fw (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1831)
[2023-12-10T09:08:32.679Z]     at async $J (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:608)
[2023-12-10T09:08:32.679Z]     at async tAA (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-12-10T09:08:32.679Z]     at async CC (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-12-10T09:08:32.679Z]     at async NeA (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2023-12-10T09:08:32.679Z]     at async MeA (/Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2023-12-10T09:08:32.682Z] Stop (12535 ms): Run: /Applications/VSCode.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lgorog/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-71a7980d-d8ed-4bc6-9910-4ea0fe67cb291702199299082 --workspace-folder /Users/lgorog/GolandProjects/nerg4l/dokku-redis --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/lgorog/GolandProjects/nerg4l/dokku-redis --id-label devcontainer.config_file=/Users/lgorog/GolandProjects/nerg4l/dokku-redis/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/lgorog/GolandProjects/nerg4l/dokku-redis/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-10T09:08:32.682Z] Exit code 1
[2023-12-10T09:08:32.685Z] Command failed: /Applications/VSCode.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/lgorog/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lgorog/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-71a7980d-d8ed-4bc6-9910-4ea0fe67cb291702199299082 --workspace-folder /Users/lgorog/GolandProjects/nerg4l/dokku-redis --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/lgorog/GolandProjects/nerg4l/dokku-redis --id-label devcontainer.config_file=/Users/lgorog/GolandProjects/nerg4l/dokku-redis/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/lgorog/GolandProjects/nerg4l/dokku-redis/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-10T09:08:32.685Z] Exit code 1
```

**Comment by josegonzalez** [comment]
Gotcha. Mind updating this pr to use jammy instead and resolve the MR conflicts?

**Comment by nerg4l** [comment]
Resolved

**Pull request merged**
